version: "3.9"
   
services:
  # db:
  #   image: mysql
  #   volumes:
  #     - ./db:/var/lib/mysql/
  web:
    build: .
    command: rails server -b 0.0.0.0 -p 3000
    volumes:
      - .:/code
    # ports:
    #   - "3000:3000"
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

    # This config is for joining this container to network
    # networks:
    #   - current-net
    # depends_on:
    #   - db

    # This config is for redirect host port to container port
    network_mode: host

# This config is for creating another network inside host
# networks:
#   current-net:
#     driver: host 